"""!
@file db_write.py
@brief Functions to modify the values in the database.

This file contains the implementation of the functions with writing access
to the database, i.e. that can modify the records contained in it. They are
grouped into three categories:

1) Functions to insert records into the database

2) Functions to update records already existing in the database

3) Functions to delete records from the database
"""

import sqlite3
from datetime import datetime





# Functions to insert records into the database

def insert_user(db:str, user_id:int, name:str, username:str) -> None:
    """! @brief Inserts a new user in the database.
    @param db: string, the path to the database file
    @param user_id: integer, ID of the user's chat with the Bot
    @param name: string, user's full name
    @param username: string, user's Telegram username (starts with @)
    @return None

    This function inserts a new user into the database, and in case their user_id
    already exists it updates the other fields to the new values.
    """
    con = sqlite3.connect(db)
    con.execute(
        """
        INSERT OR REPLACE INTO users (user_id,name,username)
        VALUES (?,?,?);
        """,
        (user_id,name,username)
    )
    con.commit()
    con.close()
    return

def insert_fair(db:str, name:str, description:str) -> None:
    """! @brief Inserts a new fair in the database.
    @param db: string, the path to the database file
    @param name: string, the fair's name in short
    @param description: string, the fair's extended description
    @return None

    This function inserts a new fair into the database. The fair's ID is not
    required, as it is automatically generated by the database.
    """
    con = sqlite3.connect(db)
    con.execute(
        """
        INSERT INTO fairs (name,description)
        VALUES (?,?);
        """,
        (name,description)
    )
    con.commit()
    con.close()
    return

def insert_event(db:str, fair_id:int, owner_id:int, name:str, description:str) -> None:
    """! @brief Inserts a new event in the database.
    @param db: string, the path to the database file
    @param fair_id: integer, ID of the fair the event belongs to
    @param owner_id: integer, ID of the user that published the event
    @param name: string, the event's name in short
    @param description: string, the event's extended description
    @return None

    This function inserts a new event into the database. The event's ID is not
    required, as it is automatically generated by the database.
    """
    con = sqlite3.connect(db)
    con.execute(
        """
        INSERT INTO events (fair_id,owner_id,name,description)
        VALUES (?,?,?,?);
        """,
        (fair_id,owner_id,name,description)
    )
    con.commit()
    con.close()
    return

def create_slot(db:str, event_id:int, start_time:datetime, end_time:datetime) -> None:
    """! @brief Creates a new slot in the database, with no user associated.
    @param db: string, the path to the database file
    @param event_id: integer, ID of the event the slot refers to
    @param start_time: datetime, date and time the slot will start
    @param end_time: datetime, date and time the slot will end
    @return None

    This function creates a new free slot in the database, i.e. a slot associated
    with the NULL user. The slot's ID is not required, as it is automatically
    generated by the database. Datetime objects are converted to ISO-8601 time strings.
    """
    con = sqlite3.connect(db)
    con.execute(
        """
        INSERT INTO slots (event_id,user_id,start_time,end_time)
        VALUES (?,?,?,?);
        """,
        (
            event_id,
            None,
            start_time.strftime("%Y-%m-%d %H:%M:%S"),
            end_time.strftime("%Y-%m-%d %H:%M:%S")
        )
    )
    con.commit()
    con.close()
    return

def create_slot_str(db:str, event_id:int, start_time:str, end_time:str) -> None:
    """! @brief Creates a new slot in the database, with no user associated.
    @param db: string, the path to the database file
    @param event_id: integer, ID of the event the slot refers to
    @param start_time: time string ISO-8601, date and time the slot will start
    @param end_time: time string ISO-8601, date and time the slot will end
    @return None

    This function creates a new free slot in the database, i.e. a slot associated
    with the NULL user. The slot's ID is not required, as it is automatically
    generated by the database. Please ensure the two time strings are formatted
    according to ISO-8601, i.e. "YYYY-MM-DD HH:MM:SS", as no format check is made.
    """
    con = sqlite3.connect(db)
    con.execute(
        """
        INSERT INTO slots (event_id,user_id,start_time,end_time)
        VALUES (?,?,?,?);
        """,
        (event_id,None,start_time,end_time)
    )
    con.commit()
    con.close()
    return

def assign_slot(db:str, slot_id:int, user_id:int|None) -> None:
    """! @brief Assigns an existing slot in the database to a user.
    @param db: string, the path to the database file
    @param slot_id: integer, ID of the slot to assign
    @param user_id: integer, user to assign the slot to, if None the
    slot is free
    @return None

    This function sets the user_id field of a slot to the desired value. It can
    be used to assign a free slot to somebody, or to modify the user of and
    already assigned slot. To turn free an occupied slot, simply pass the None
    value as <code>user_id</code>.
    """
    con = sqlite3.connect(db)
    con.execute(
        """
        UPDATE slots SET user_id=?
        WHERE slot_id=?;
        """,
        (user_id, slot_id)
    )
    con.commit()
    con.close()
    return





# Functions to update records already existing in the database

def update_user(db:str, user_id:int, name:str, username:str) -> None:
    """! @brief Updates a user in the database.
    @param db: string, the path to the database file
    @param user_id: integer, ID of the user to modify
    @param name: string, the user's new name
    @param username: string, the user's new Telegram username (starts with @)
    @return None

    This function modifies a user already existing in the database.
    <code>insert_user</code> can be used to modify a user as well, but
    <code>insert_user</code> is to be preferred when you are sure the
    user already exists.
    """
    con = sqlite3.connect(db)
    con.execute(
        """
        UPDATE users SET name=?, username=?
        WHERE user_id=?;
        """,
        (name,username,user_id)
    )
    con.commit()
    con.close()
    return

def update_fair(db:str, fair_id:int, name:str, description:str) -> None:
    """! @brief Updates a fair in the database.
    @param db: string, the path to the database file
    @param fair_id: integer, ID of the fair to modify
    @param name: string, the fair's new name
    @param description: string, the fair's new description
    @return None

    This function modifies a fair already existing in the database.
    """
    con = sqlite3.connect(db)
    con.execute(
        """
        UPDATE fairs SET name=?, description=?
        WHERE fair_id=?;
        """,
        (name,description,fair_id)
    )
    con.commit()
    con.close()
    return

def update_event(
        db:str,
        event_id:int,
        fair_id:int,
        owner_id:int,
        name:str,
        description:str
) -> None:
    """! @brief Updates an event in the database.
    @param db: string, the path to the database file
    @param event_id: integer, ID of the event to modify
    @param fair_id: integer, the new fair to assign the event to
    @param owner_id: integer, the user ID of the event's new owner
    @param name: string, the event's new name
    @param description: string, the event's new description
    @return None

    This function modifies an event already existing in the database.
    """
    con = sqlite3.connect(db)
    con.execute(
        """
        UPDATE events SET fair_id=?, owner_id=?, name=?, description=?
        WHERE event_id=?;
        """,
        (fair_id,owner_id,name,description,event_id)
    )
    con.commit()
    con.close()
    return

def update_event_description(db:str, event_id:int, description:str) -> None:
    """! @brief Updates the description of an event in the database.
    @param db: string, the path to the database file
    @param event_id: integer, ID of the event to modify
    @param description: string, the event's new description
    @return None

    This function is a specialization of <code>update_event</code> that modifies
    only the <code>description</code> field of the event, since this is the element
    that is most likely to change for this table.
    """
    con = sqlite3.connect(db)
    con.execute(
        """
        UPDATE events SET description=?
        WHERE event_id=?;
        """,
        (description,event_id)
    )
    con.commit()
    con.close()
    return

def update_slot(
        db:str,
        slot_id:int,
        event_id:int,
        user_id:int|None,
        start_time:datetime,
        end_time:datetime
) -> None:
    """! @brief Updates a slot in the database.
    @param db: string, the path to the database file
    @param slot_id: integer, ID of the slot to modify
    @param event_id: integer, ID of the new event the slot refers to
    @param user_id: integer, ID of the new user assigned to this slot, if None the
    slot becomes free
    @param start_time: datetime, new date and time the slot will start
    @param end_time: datetime, new date and time the slot will end
    @return None

    This function modifies a slot already existing in the database. If you want the
    slot to become free, simply pass the None value as <code>user_id</code>.
    In case the slot change involves only the field <code>user_id</code>, then
    <code>assign_slot</code> function is to be preferred.
    """
    con = sqlite3.connect(db)
    con.execute(
        """
        UPDATE slots SET event_id=?,user_id=?,start_time=?,end_time=?
        WHERE slot_id=?;
        """,
        (
            event_id,
            user_id,
            start_time.strftime("%Y-%m-%d %H:%M:%S"),
            end_time.strftime("%Y-%m-%d %H:%M:%S"),
            slot_id
        )
    )
    con.commit()
    con.close()
    return





# Functions to delete records of the database

def delete_user(db:str, user_id:int) -> None:
    """! @brief Deletes a user in the database.
    @param db: string, the path to the database file
    @param user_id: integer, ID of the user to delete
    @return None

    This function deletes a user already existing in the database.
    """
    con = sqlite3.connect(db)
    con.execute(
        """
        DELETE FROM users
        WHERE user_id=?;
        """,
        (user_id,)
    )
    con.commit()
    con.close()
    return

def delete_fair(db:str, fair_id:int) -> None:
    """! @brief Deletes a fair in the database.
    @param db: string, the path to the database file
    @param fair_id: integer, ID of the fair to delete
    @return None

    This function deletes a fair already existing in the database.
    """
    con = sqlite3.connect(db)
    con.execute(
        """
        DELETE FROM fairs
        WHERE fair_id=?;
        """,
        (fair_id,)
    )
    con.commit()
    con.close()
    return

def delete_event(db:str, event_id:int, delete_slots:bool=True) -> None:
    """! @brief Deletes an event in the database.
    @param db: string, the path to the database file
    @param event_id: integer, ID of the event to delete
    @param delete_slots: boolean, if true all the slots liked to this
    event are deleted as well
    @return None

    This function deletes an event already existing in the database. In case
    <code>delete_slots</code> is set to True, then all the slots linked to
    this event are deleted as well.
    """
    con = sqlite3.connect(db)

    con.execute(
        """
        DELETE FROM events
        WHERE event_id=?;
        """,
        (event_id,)
    )
    if delete_slots:
        con.execute(
            """
            DELETE FROM slots
            WHERE event_id=?;
            """,
            (event_id,)
        )

    con.commit()
    con.close()
    return

def delete_slot(db:str, slot_id:int) -> None:
    """! @brief Deletes a slot in the database.
    @param db: string, the path to the database file
    @param slot_id: integer, ID of the slot to delete
    @return None

    This function deletes a slot already existing in the database. Nothing happens
    to the event this slot refers to.
    """
    con = sqlite3.connect(db)
    con.execute(
        """
        DELETE FROM slots
        WHERE slot_id=?;
        """,
        (slot_id,)
    )
    con.commit()
    con.close()
    return
